### ISSUE TITLE
App Crash when download video on iOS 16

### ISSUE THREAD

**Issue by bactranngoc** [Cyklet/VidLoader#41]
Hi @Cyklet 
I tried to download a video on ios 16, but it always crashes. The problem:
`Must respond with a contentType contained in AVAssetResourceLoadingContentInformationRequest.allowedContentTypes.
`-> I think the response.mimeType has some change. So contentInformationRequest?.contentType wasn't setup correctly.

**Comment by Cyklet** [comment]
Hi @bacfabbi I think it can be thing described by mufumade in the stackoverflow https://stackoverflow.com/questions/45670774/playing-offline-hls-with-aes-128-encryption-ios/73436531#73436531

I will try to make some time and take a look

**Comment by bacfabbi** [comment]
@Cyklet 
I tried it, but it's not working. Video can't play after download or sometimes It occur an error

**Comment by Cyklet** [comment]
@bacfabbi can you provide an URL I have tried some from my side and it's not crashing, still I have some issues with downloading in iOS 16 that I am trying to fix but no crashes yet.

**Comment by bacfabbi** [comment]
@Cyklet 
This pull is not working on ios 16, I can't play it after downloading the video.
https://github.com/Cyklet/VidLoader/pull/42
Please check with this URL.
https://www2.uliza.jp/IF/iphone/iPhonePlaylist.m3u8?v=259401-1070457&p=6141&d=629&n=1698&t=8ae9b3222d506dfda9ca9ef9039257fa&previewflag=0&logging=1

**Comment by Cyklet** [comment]
Hi @bacfabbi I have pushed a fix for content allowed types, I have tested with provided link from you. If it's not fix please feel free to reopen issue

**Comment by bacfabbi** [comment]
Hi @Cyklet 
Thank you for fixing but It's still not working, I have tried this way before but the video can't play after downloading is completed. I tried to download with another way, It's working with my URL but not working with your URL.
https://www2.uliza.jp/IF/iphone/iPhonePlaylist.m3u8?v=259884-1071964&p=6141&d=629&n=7351&t=353ddc5d62e7e5b8cc69b6ac52256411&previewflag=0&logging=1

**Comment by Cyklet** [comment]
Hi @bacfabbi if you open this link in the safari it is black window and contains only sound in it, is it expected behaviour?

**Comment by ToThangGTVT** [comment]
This is new link: https://www2.uliza.jp/IF/iphone/iPhonePlaylist.m3u8?v=260020-1072112&p=3006&d=629&n=7351&t=13683a203d0b3e32df1b70c3b4cf419e&maxbit=2000&minbit=364&previewflag=0
You can play it at https://www.hlsplayer.net and after time period, it will expired

**Comment by Cyklet** [comment]
Hi @bacfabbi , @ToThangGTVT -> https://github.com/Cyklet/VidLoader/pull/46 I have checked and revert the return logic from delegate. As a temporary solution I have added an artificial delay for the master data loading, even if apple documentation is saying that **You can load the resource synchronously or asynchronously** it seems that for iOS 16 is not the case.

Reference: https://developer.apple.com/documentation/avfoundation/avassetresourceloaderdelegate/1388121-resourceloader?language=objc

**Comment by bacfabbi** [comment]
Hi @Cyklet 
But it's not working. I will give you the API to get my streaming URL. It will be easier to check.

**Comment by Cyklet** [comment]
@bacfabbi I have tried @ToThangGTVT link and it was working :( if you can share a new one I will take a look again.

**Comment by ToThangGTVT** [comment]
@Cyklet 
For reasons of security, I used Heroku to redirect the m3u8 link to you.
You can check it here.
https://test-api-mongo.herokuapp.com/episode-test

**Comment by Cyklet** [comment]
Hi @ToThangGTVT I can't acces the page:
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.
There was an unexpected error (type=Internal Server Error, status=500).

**Comment by Cyklet** [comment]
Ok @ToThangGTVT now it displays, I will take a look and try to find out why download/play is not working

**Comment by Cyklet** [comment]
I was able to reproduce the issue but it's random sometimes it works sometimes it fails, my single assumption is that again with iOS 16 AVFoundation sync load is not working as expected and keys are loaded also without any delay and finishLoading is called before return from the shouldWaitForLoadingOfRequestedResource delegate.

I will try to add an artificial delay for keys same as for master, I will read more about this as it becomes unreliable.

**Comment by ToThangGTVT** [comment]
@Cyklet 
With your example project, the video can not play when I turn off the internet and is available to play when I turn on the internet.
This is a evidence.
https://drive.google.com/file/d/1zFCsSlsO2b0PpAX96XgxsCjHHDc9J24Q/view?usp=sharing

**Comment by Cyklet** [comment]
Hi, I have noticed that in iOS 16
 ```
func resourceLoader(_ resourceLoader: AVAssetResourceLoader,
                        shouldWaitForLoadingOfRequestedResource loadingRequest: AVAssetResourceLoadingRequest) -> Bool {
```
is behaving differently, it is called multiple times for the same resource that caused the issue that you have.
I have updated the code taking the URL scheme as source of truth, I have split the custom scheme in 2 schemes:
- variant scheme -> vidloader-variant
- master scheme -> vidloader-master

I have tested few urls wwdc/yours/other streams from the internet and it is working without any error.

Can you please check #48 one and see if it's working on your side too.

Thanks ;)

**Comment by bactranngoc** [comment]
@Cyklet 
Thank you so much for supporting.
I will check in my side

**Comment by bactranngoc** [comment]
@Cyklet 
Sorry for the late reply.
I have confirmed on iOS 16.1 and other OS version. It's work. The bug has been fixed.
Thank you so much for your support.
